spring.application.name=enterprise

spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise
spring.datasource.username=postgres
spring.datasource.password=rootuser
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

secretkey=6B8E2A0F7D6C34E0B1F8A9D2C7F5E9A12C4B7D3F5A9E6C0D1F2B8C7A1E3F9B6!@#$

student.image.upload-dir=C:/Users/ASUS/Desktop/enterprise/
faculty.upload-dir=C:/Users/ASUS/Desktop/enterprise/faculty/

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


